// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// WeatherByCepHandler is an autogenerated mock type for the WeatherByCepHandler type
type WeatherByCepHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: w, r
func (_m *WeatherByCepHandler) Handle(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewWeatherByCepHandler creates a new instance of WeatherByCepHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeatherByCepHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeatherByCepHandler {
	mock := &WeatherByCepHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
