FROM golang:1.23.2 AS build
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o weather ./cmd

FROM alpine:latest
WORKDIR /app
COPY --from=build /app/weather .
ENTRYPOINT ["./weather"]
