// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// WeatherClient is an autogenerated mock type for the WeatherClient type
type WeatherClient struct {
	mock.Mock
}

// WeatherByCity provides a mock function with given fields: tx, city
func (_m *WeatherClient) WeatherByCity(tx context.Context, city string) (float64, error) {
	ret := _m.Called(tx, city)

	if len(ret) == 0 {
		panic("no return value specified for WeatherByCity")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(tx, city)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(tx, city)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(tx, city)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWeatherClient creates a new instance of WeatherClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeatherClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeatherClient {
	mock := &WeatherClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
